import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import ExploreLayout from "@/layout/explore.layout";
import { ThemeProvider } from "@/components/themes-provider";
import { SearchProvider } from "@/components/context/search.context";
import { FilterProvider } from "@/components/context/filter.context";
import { Inter } from 'next/font/google'

config.autoAddCss = false;
const inter = Inter({
    subsets: ['latin'],
    display: 'swap', // Quan trọng!
    preload: true,
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className} suppressHydrationWarning>
            <body
                className={`dark:bg-gray-800 ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <FilterProvider>
                        <SearchProvider>
                            <ExploreLayout>
                                {children}
                            </ExploreLayout>
                        </SearchProvider>
                    </FilterProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
